base_link_frame: base_fooftprint
odom_frame: odom
world_frame: map
two_d_mode: true
frequency: 50

#use_control: true
control_config: [true, false, false,
                 false, false, true]

odom0: /odom0_input
# (X,Y,Z,roll,pitch,yaw,X˙,Y˙,Z˙,roll˙,pitch˙,yaw˙,X¨,Y¨,Z¨)
odom0_config: [true, true, false,
               false, false, true,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: true
odom0_relative: false
odom0_queue_size: 10

pose0: /pose0_input
# (X,Y,Z,roll,pitch,yaw,X˙,Y˙,Z˙,roll˙,pitch˙,yaw˙,X¨,Y¨,Z¨)
pose0_config: [true, true, false,
              true, true, true,
              false, false, false,
              false, false, false,
              false, false, false]
pose0_differential: true
pose0_relative: false
pose0_queue_size: 1


debug: false
debug_out_file: dekfloc.txt
print_diagnostic: false