joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['base_to_r_f_wheel', 'base_to_r_b_wheel']
  right_wheel: ['base_to_l_f_wheel', 'base_to_l_b_wheel']
  publish_rate: 50
  pose_covariance_diagonal: [0.01, 0.01, 1000000.0, 1000000.0, 1000000.0, 100.0]
  twist_covariance_diagonal: [0.01, 1.0, 1000000.0, 1000000.0, 1000000.0, 100.0]
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: root_link
  allow_multiple_cmd_vel_publishers: true


  enable_odom_tf: true

  # Wheel separation and radius
  wheel_separation: 0.4 # default: by model
  wheel_radius    : 0.075 # default: by model
  wheel_separation_multiplier: 2.5 # default: 1.0
  wheel_radius_multiplier    : 1 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 3.0   # rad/s^2
