joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

wheel_fl_vel_controller:
    type: "effort_controllers/JointVelocityController"
    joint: wheel_joint_fl
    pid: {p: 1.0, i: 1.0, d: 0.0}
wheel_bl_vel_controller:
    type: "effort_controllers/JointVelocityController"
    joint: wheel_joint_bl
    pid: {p: 1.0, i: 1.0, d: 0.0}
wheel_fr_vel_controller:
    type: "effort_controllers/JointVelocityController"
    joint: wheel_joint_fr
    pid: {p: 1.0, i: 1.0, d: 0.0}
wheel_br_vel_controller:
    type: "effort_controllers/JointVelocityController"
    joint: wheel_joint_br
    pid: {p: 1.0, i: 1.0, d: 0.0}

diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['wheel_joint_fl', 'wheel_joint_bl']
  right_wheel: ['wheel_joint_fr', 'wheel_joint_br']
  publish_rate: 50
  pose_covariance_diagonal: [0.01, 0.01, 1000000.0, 1000000.0, 1000000.0, 100.0]
  twist_covariance_diagonal: [0.01, 1.0, 1000000.0, 1000000.0, 1000000.0, 100.0]
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_link
  allow_multiple_cmd_vel_publishers: true


  enable_odom_tf: true

  # Wheel separation and radius
  wheel_separation: 0.4 # default: by model
  wheel_radius    : 0.075 # default: by model
  wheel_separation_multiplier: 2.5 # default: 1.0
  wheel_radius_multiplier    : 1 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 3.0   # rad/s^2
