# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
standalone_tags:
   [
     {id: 125, size: 0.125, name: "__125__"},
     {id: 276, size: 0.176, name: "__276__"},
     {id: 0, size: 0.173, name: "ids_xs_camera_L/robot_0"},
     #{id: 2, size: 0.173, name: "map_2"},
     #{id: 3, size: 0.173, name: "map_3"},
     #{id: 4, size: 0.173, name: "map_4"}
   ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: "/map",
      layout:
        [
          {id: 1, size: 0.173, x: 0, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}, # <^
          {id: 2, size: 0.173, x: 0.639, y: 0.003, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}, # ^>
          {id: 3, size: 0.173, x: 0.643, y: -0.855, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}, # _>
          {id: 4, size: 0.173, x: 0, y: 2, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}  # <_
        ]
    },
    {
      name: "robot_1",
      layout:
        [
          {id: 10, size: 0.173, x: 0, y: -0.1, z: 0, qw: 0.707, qx: 0.707, qy: 0, qz: 0},
          {id: 11, size: 0.173, x: 0.1, y: 0, z: 0, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 12, size: 0.173, x: 0, y: 0.1, z: 0, qw: 0, qx: 0, qy: 0.707, qz: 0.707},
          {id: 13, size: 0.173, x: -0.1, y: 0, z: 0, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5}
        ]
    },
    {
      name: "robot_2",
      layout:
        [
          {id: 14, size: 0.173, x: 0, y: -0.1, z: 0, qw: 0.707, qx: 0.707, qy: 0, qz: 0},
          {id: 15, size: 0.173, x: 0.1, y: 0, z: 0, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 16, size: 0.173, x: 0, y: 0.1, z: 0, qw: 0, qx: 0, qy: 0.707, qz: 0.707},
          {id: 17, size: 0.173, x: -0.1, y: 0, z: 0, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5}
        ]
    }
  ]
